# Generated by Django 5.2.8 on 2025-11-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyledImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('text', models.TextField()),
                ('font_size', models.IntegerField(default=36)),
                ('font_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('x_position', models.IntegerField(default=50)),
                ('y_position', models.IntegerField(default=50)),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='outputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
