# Generated by Django 5.2.8 on 2025-11-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='styledimage',
            name='font_family',
            field=models.CharField(default='Arial', max_length=50),
        ),
    ]
