# Generated by Django 5.2.8 on 2025-11-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styler', '0003_category_alter_styledimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='styledimage',
            name='enable_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='enable_shadow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='font_weight',
            field=models.CharField(choices=[('100', 'Thin'), ('200', 'Extra Light'), ('300', 'Light'), ('400', 'Regular'), ('500', 'Medium'), ('600', 'Semi Bold'), ('700', 'Bold'), ('800', 'Extra Bold'), ('900', 'Black')], default='600', max_length=10),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='letter_spacing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='line_height',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='shadow_blur',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='shadow_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='shadow_x',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='shadow_y',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='text_background',
            field=models.CharField(default='#00000000', max_length=9),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='text_opacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='text_rotate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='styledimage',
            name='font_family',
            field=models.CharField(default='Roboto', max_length=100),
        ),
    ]
