# Generated by Django 5.2.8 on 2025-11-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styler', '0004_styledimage_enable_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, help_text='Representative image for this category', null=True, upload_to='category_images/'),
        ),
    ]
