# Generated by Django 5.2.8 on 2025-12-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styler', '0005_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styledimage',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_landing',
            field=models.BooleanField(default=False, help_text='Show this category in the landing page'),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time the image was updated', verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='update_clicks',
            field=models.IntegerField(default=0, help_text='Number of times this image was updated via API', verbose_name='Update Clicks'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
