# Generated by Django 5.2.8 on 2025-12-04 22:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styler', '0006_remove_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Keyword or tag name (e.g., birthday, quote, inspirational)', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the tag name', max_length=60, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the tag', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Custom meta title for this tag page', max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Custom meta description for this tag page', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this tag is used')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['landing_order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='styledimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Styled Image', 'verbose_name_plural': 'Styled Images'},
        ),
        migrations.AddField(
            model_name='category',
            name='image_count',
            field=models.IntegerField(default=0, help_text='Number of images in this category (auto-updated)'),
        ),
        migrations.AddField(
            model_name='category',
            name='landing_order',
            field=models.IntegerField(default=0, help_text='Order in which categories appear on landing page (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Custom meta description for category page (if empty, uses description)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom meta title for category page (if empty, uses name)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for this category', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly category name (auto-generated if empty)', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='total_clicks',
            field=models.IntegerField(default=0, help_text='Total update clicks for images in this category'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='styled_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description for SEO and search', null=True),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='download_count',
            field=models.IntegerField(default=0, help_text='Number of times this image was downloaded'),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='image_name',
            field=models.CharField(blank=True, help_text='Descriptive name for the image (important for SEO)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this image in search results'),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Make this image publicly accessible'),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Full-text search vector (PostgreSQL only)', null=True),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Custom SEO description', null=True),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for this image', null=True),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom SEO title (if empty, uses image_name or text)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='stroke_color',
            field=models.CharField(default='#000000', help_text='Stroke color', max_length=7),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='stroke_width',
            field=models.IntegerField(default=1, help_text='Stroke width in pixels'),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='text_padding',
            field=models.IntegerField(default=0, help_text='Padding around text in pixels'),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='text_stroke',
            field=models.BooleanField(default=False, help_text='Add stroke outline to text'),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Small thumbnail for listings (auto-generated)', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user who created this image', null=True),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times this image was viewed'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, help_text='Representative image for this category (Recommended: 1200x630px)', null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the category', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (e.g., Quotes, Birthday, Business)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='styledimage',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for this image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='styled_images', to='styler.category'),
        ),
        migrations.AlterField(
            model_name='styledimage',
            name='letter_spacing',
            field=models.FloatField(default=0.0, help_text='Letter spacing in pixels'),
        ),
        migrations.AlterField(
            model_name='styledimage',
            name='line_height',
            field=models.FloatField(default=1.2, help_text='Line height multiplier'),
        ),
        migrations.AlterField(
            model_name='styledimage',
            name='original_image',
            field=models.ImageField(help_text='Original uploaded image', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='styledimage',
            name='output_image',
            field=models.ImageField(blank=True, help_text='Styled output image with text', null=True, upload_to='outputs/'),
        ),
        migrations.AlterField(
            model_name='styledimage',
            name='text',
            field=models.TextField(help_text='Text to display on the image'),
        ),
        migrations.AlterField(
            model_name='styledimage',
            name='text_opacity',
            field=models.IntegerField(default=100, help_text='Text opacity percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='styledimage',
            name='text_rotate',
            field=models.IntegerField(default=0, help_text='Text rotation in degrees (-180 to 180)'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='styler_cate_slug_290552_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['show_in_landing'], name='styler_cate_show_in_775d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['landing_order'], name='styler_cate_landing_83498b_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='styler_tag_slug_1b9be6_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['usage_count'], name='styler_tag_usage_c_752c3e_idx'),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Keywords/tags for search optimization', related_name='styled_images', to='styler.tag'),
        ),
        migrations.AddIndex(
            model_name='styledimage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='styler_styl_search__b94f3f_gin'),
        ),
        migrations.AddIndex(
            model_name='styledimage',
            index=models.Index(fields=['image_name'], name='styler_styl_image_n_1eb814_idx'),
        ),
        migrations.AddIndex(
            model_name='styledimage',
            index=models.Index(fields=['created_at'], name='styler_styl_created_c31035_idx'),
        ),
        migrations.AddIndex(
            model_name='styledimage',
            index=models.Index(fields=['update_clicks'], name='styler_styl_update__4bcb35_idx'),
        ),
        migrations.AddIndex(
            model_name='styledimage',
            index=models.Index(fields=['is_featured'], name='styler_styl_is_feat_bbe068_idx'),
        ),
        migrations.AddIndex(
            model_name='styledimage',
            index=models.Index(fields=['is_public'], name='styler_styl_is_publ_5d4d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='styledimage',
            index=models.Index(fields=['category', 'created_at'], name='styler_styl_categor_23779d_idx'),
        ),
    ]
