# Generated by Django 5.2.8 on 2025-12-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styler', '0007_tag_alter_category_options_alter_styledimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='styler_cate_slug_290552_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='styler_cate_show_in_775d2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='styler_cate_landing_83498b_idx',
        ),
        migrations.RemoveIndex(
            model_name='styledimage',
            name='styler_styl_search__b94f3f_gin',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='styler_tag_slug_1b9be6_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='styler_tag_usage_c_752c3e_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='landing_order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='styledimage',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='category',
            name='total_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, help_text='Representative image for this category', null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (if empty, uses description)', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (if empty, uses name)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='total_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
