# Generated by Django 5.2.8 on 2025-12-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styler', '0009_remove_styledimage_tags_alter_styledimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='styledimage',
            name='image_name',
            field=models.CharField(blank=True, help_text='Custom name for this image', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='styledimage',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this image', related_name='styled_images', to='styler.tag'),
        ),
    ]
